### ISSUE TITLE
Suggestion: protection for projectile impact?

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/GriefPreventionPlus-SkyBlock#21]
Not sure if there's a way to do it, but would be nice to have protection against modded projectiles impact. They could be set as dead when cancelled.

**Comment by KaiKikuchi** [comment]
GPPSkyBlock can't offer anything like that. And you've already asked for that on ForgeRestrictor, where it is more appropriate but I've already explained you that it's not a thing that can be done with Bukkit. A forge-side mod is needed, and that may not be enough because mods do dumb things sometimes.
