### ISSUE TITLE
Cannot use per-group permissions

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/GriefPreventionPlus-SkyBlock#27]
Not sure why, but I can't allow only MODs use the `/is setspawn` command. I currently have the `gppskyblock.setspawn` permission false for the `default` group, and true for the `mod` group, but mods can't still use the command. I'm using LuckPerms as permission manager, and I can define per-group permissions for other plugins, just not GPP-SkyBlock.

**Comment by KaiKikuchi** [comment]
I'm sorry but this is not related to this plugin. It's using a normal permission (gppskyblock.setspawn, I reviewed the code) and it works exactly like any other plugin. Be sure you have followed the permission plugin documentation and eventually try again or report the issue to the permission plugin author.

**Comment by Eufranio** [comment]
I did, and reported (via Discord), and tested with other plugins. I only cant set per-group permissions with GPP-Skyblock. Its not perm plugin fault, and if it isn't GPP-Skyblock related, what is the issue then?

**Comment by KaiKikuchi** [comment]
I am sorry but really you would have issue with a lot of plugins because they're all using the same exact API method. I think LuckPerms has a debug mode, you may want to use that to check what is happening with that exact permission. Maybe you set the permission to true for some parent group that has an higher priority than the child group. Anyway, this is really beyond the code of this plugin. For reference, this is the line of code related to this issue: https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/blob/master/src/main/java/net/kaikk/mc/gpp/skyblock/CommandExec.java#L296

I'm quite sure anyone can tell it's not this plugin's fault. Maybe you could try giving a higher priority to the child group where you set the permission to false. Also you can manually edit the plugins.yml file and force the plugin to set the permission to false by default: https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/blob/master/src/main/resources/plugin.yml#L17-L18

**Comment by Eufranio** [comment]
Thanks.
